class Autogenerated {
  int? registrationId;
  String? registrationStatus;
  String? approvedBy;
  dynamic expiredDate;
  dynamic faceImage;
  String? plateNumber;
  int? userId;
  String? updatedAt;
  String? createdAt;

  Autogenerated(
      {this.registrationId,
      this.registrationStatus,
      this.approvedBy,
      this.expiredDate,
      this.faceImage,
      this.plateNumber,
      this.userId,
      this.updatedAt,
      this.createdAt});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    registrationId = json['registrationId'];
    registrationStatus = json['registrationStatus'];
    approvedBy = json['approvedBy'];
    expiredDate = json['expiredDate'];
    faceImage = json['faceImage'];
    plateNumber = json['plateNumber'];
    userId = json['userId'];
    updatedAt = json['updatedAt'];
    createdAt = json['createdAt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['registrationId'] = this.registrationId;
    data['registrationStatus'] = this.registrationStatus;
    data['approvedBy'] = this.approvedBy;
    data['expiredDate'] = this.expiredDate;
    data['faceImage'] = this.faceImage;
    data['plateNumber'] = this.plateNumber;
    data['userId'] = this.userId;
    data['updatedAt'] = this.updatedAt;
    data['createdAt'] = this.createdAt;
    return data;
  }
}